---
name: Build containers

on:
  push:
  pull_request:

jobs:
  get_json_versions:
    runs-on: ubuntu-latest
    steps:
      # Fetch versions to work for images
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - id: set-versions
        run: echo "::set-output name=versions::$(./get_json_versions.py)"

    outputs:
      versions: ${{ steps.set-versions.outputs.versions }}

  build_images:
    runs-on: ubuntu-latest
    needs: get_json_versions
    strategy:
      fail-fast: false
      matrix:
        ps-version: ${{ fromJson(needs.get_json_versions.outputs.versions) }}
    steps:
      - uses: actions/checkout@v2
      - name: Build Docker image
        run: docker build images/${version}
